[shell]
args = ['--login']
program = "/usr/bin/zsh"

[cursor]
style = "Beam"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 10
y = 10

#[window.dimensions]
#columns = 90
#lines = 25

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#e7e7ec"
foreground = "#2b2b2c"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

